language: cpp
sudo: required
python:          3.6
dist:            trusty

matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - zlib1g-dev
            - libbz2-dev
            - libboost-dev
            - cmake
            - cmake-data
            - make

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7

script:
  - mkdir build && cd build
  - cmake .. # -DBUILD_BIN=1 ..
  - make

branches:
  only:
  - master